project:
  type: website

website:
  title: "Swapnanil SenGupta"
  site-url: "https://swapnanilsengupta.com"
  description: "PhD candidate at the Halle Institute for Economic Research (IWH), working in macroeconomics, environmental economics and labour economics."

  navbar:
    search: true

    right:
      - text: Research
        href: research.qmd
      - text: CV
        href: cv.qmd
      - text: Awards
        href: awards.qmd
      - text: Beyond Economics
        href: beyond.qmd
      - text: Contact
        href: contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    include-after-body: analytics.html